# ==========================================
# CẤU HÌNH CƠ BẢN (Gateway làm Lễ tân ở cổng 8080)
# ==========================================
server.port=8900
spring.application.name=api-gateway
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# ==========================================
# SPRING CLOUD GATEWAY ROUTES (Chỉ đường chuẩn)
# ==========================================

# 1. User service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**, /register/**, /registration/**, /login/**

# 2. Product service
spring.cloud.gateway.routes[1].id=product-catalog-service
spring.cloud.gateway.routes[1].uri=lb://product-catalog-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**

# 3. Recommendation service
spring.cloud.gateway.routes[2].id=product-recommendation-service
spring.cloud.gateway.routes[2].uri=lb://product-recommendation-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/*/recommendations/**, /recommendations/**

# 4. Order service
spring.cloud.gateway.routes[3].id=order-service
spring.cloud.gateway.routes[3].uri=lb://order-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/order/**, /orders/**, /cart/**

# 5. Payment service (HÀNG MỚI THÊM VÀO ĐÂY)
spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://payment-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/payments/**

# ==========================================
# SPRING SESSION & REDIS (Để làm chức năng Giỏ hàng)
# ==========================================
spring.session.store-type=redis
spring.session.redis.namespace=session
spring.session.redis.flush-mode=on-save
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cấu hình CORS
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*